package com.example.krishbhatia.eduassets;

public class Constants {
    public static final String USER_ID ="USER_ID" ;
    public static final String NOT_FOUND = "NOT_FOUND";
    public static final String EMAIL ="EMAIL" ;
    public static final String USERPOJO = "USER_POJO";
    public static final String COURSE_NAME = "courseName";
    public static final String UNIVERSITY_NAME = "universityName";
    public static final String USERS = "users";
    public static final String URL = "url";
    public static final String NAME = "name";
    public static final String COURSE = "course";
    public static final String COURSE_ABBREVIATION = "courseAbbreviation";
    public static final String UNIVERSITY = "university";
    public static final String SEMESTER = "semester";
    public static final String COLLEGE = "college";
    public static final String COURSE_ID = "courseId";
    public static final String UNIVERSITY_CODE = "universityCode";
    public static final String SAVE_CHANGES = "Save Changes?";
    public static final String SELECTED_SUBJECT = "SELECTED_SUBJECT";
    public static final String PDF = "pdf";
    public static final String VIDEO = "video";
    public static final String ALL_COURSES = "All Courses";
    public static final String MY_SUBJECTS = "My Subjects";
    public static final String USERS_FIREBASE = "users";
    public static final String  SUBJECT_BASIC_INFO = "subjectBasicInfo";
    public static final String MY_ROOT = "MyRoot";
    public static final String RES = "res";
    public static final String YES = "Yes";
    public static final String NO = "No";
    public static final String EMPTY_FIELD_TOAST = "Fields must not be empty";
    public static final String EMAIL_SMALL = "email";
    public static final String CHECK_YOUR_INTERNET_CONNECTION = "Check Your Internet Connection";
    public static final String SYLLABUS = "Syllabus";
    public static final String COURSE_BASIC_INFO = "courseBasicInfo";
    public static final String UNIVERSITY_INFO = "universityInfo";
    public static final String SUBJECT_CODE = "subjectCode";
    public static final long DEFAULT_VALUE = -1;
    public static final String SELECT_COURSE = "Select Course";
    public static final String SELECT_UNIVERSITY = "Select University";
    public static final String OTHER = "Other";
    public static final String RESOURCE_NAME = "resource name";
}
